feat :sparkles: : Added Timer + TimerButton + Formater
PrzemekChociaj/Workout-Page pull request #2
Opened 2023-07-04 12:46 UTC by PrzemekChociaj

2023-07-04 18:59 UTC, qbawalat requested changes

2023-07-04 18:59 UTC, qbawalat commented on src/components/Features/Formater.tsx
> +    const minutes = Math.floor(time / 60);
60 is magic number - extract to const e.g. MINUTES_IN_ONE_HOUR

2023-07-04 18:59 UTC, qbawalat commented on src/components/Features/TimerButton.tsx
> +const TimerButton = ({ isRunning, toggleTimer }) => {
Missing FunctionComponent<Props> type

2023-07-04 18:59 UTC, qbawalat commented on src/components/Timer/Timer.tsx
> +const Timer: React.FunctionComponent = () => {
1. Don't import react
2. 2Dont use React.FunctionCOmponent - import FUnctionComponent from React and just write TImer: FunctionComponent

2023-07-04 18:59 UTC, qbawalat commented on src/components/Timer/Timer.tsx
> +
extract to custom hook e.g. useTimer

2023-07-05 10:47 UTC, khali16 requested changes

2023-07-05 10:47 UTC, khali16 commented on src/components/Features/Formater.tsx
> +export const formatTime = (time: number) => {
Missing return type

2023-07-05 10:47 UTC, khali16 commented on src/components/Features/TimerButton.tsx
> +				isRunning
Conditional styles should be extracted to a separate function

2023-07-05 13:12 UTC, khali16 commented on src/components/Features/TimerButton.tsx
> +const ButtonClassName = (isRunning: boolean): string => {
- It is a function so you should change naming convention - e.g. getButtonColor;
- no need for bracers and return statement - use oneliner function

2023-07-06 12:32 UTC, merged